version: '3.9'

services:
  # Mongodb services
  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db
  
  #API service
  depo_api:
    container_name: depo_api
    build: .
    ports:
      - 8080:8080
    environment:
      HTTP: 8080
      MONGO_URL: mongodb://mongo:27017
      DB_NAME: depo
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
